# -*- coding: utf-8 -*-
"""Actividad_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fe4L2mc8Asn6MGAKa23xyuL3ZmOrh-Qb
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from sklearn.cluster import KMeans

img = mpimg.imread('bubblegum.jpg')

w, h, d = img.shape

x = np.reshape(img,(w*h,d))

n = 4

model = KMeans(n_clusters=n)
model.fit(x)

y_pred = model.predict(x)

C = model.cluster_centers_
I = np.reshape(y_pred,(w,h))

#print(C)

img_out = np.zeros((w,h,d))

for i in range(w):
  for j in range(h):
    for k in range(d):
      img_out[i][j][k] = C[I[i][j]][k]

img_out = img_out.astype(int)

plt.figure()
plt.title('Imagen Original')
plt.imshow(img)
plt.show()

plt.figure
plt.title('Imagen Cuantizada')
plt.imshow(img_out)
plt.show()